# http://travis-ci.org/#!/mozilla/crontabber

# This indicates to Travis that we will not use or need sudo
# so that we can benefit from and use the cache->directories
# directive.
sudo: no

env: PIP_DOWNLOAD_CACHE="pip_cache"
cache:
    directories:
        - pip_cache

language: python

python:
    - 2.7

addons:
    postgresql: "9.4"

before_install:
    - travis_retry pip install -r test-requirements.txt
    - psql -c 'create database travis_ci_test;' -U postgres
    - travis_retry pip install twine

install:
    - python setup.py install

script:
    - user=postgres dbname=travis_ci_test nosetests crontabber --with-cover --cover-erase --cover-package=crontabber

notifications:
    irc:
        channels: "irc.mozilla.org#breakpad"

after_success:
    # so that builds can be made with a reStructuredText README
    - travis_retry pip install pypandoc
    # Report coverage results to coveralls.io
    - travis_retry pip install coveralls
    - coveralls

deploy:
    provider: pypi
    user: peterbe
    password:
        secure: WtHO5O92hH46GHeIJBlkwMgkF/oLiftIsC9Ff9bl00+vTk97NdnvGjfLa78haJIs1WNOm+gKhzIAF/q/cipJ2wdGQRoZ178NhZimhamUMfDQoaNPolKfFSQ6uA+GLQPXo7N/AGH18S8AwCwTcWObaUTQhnAxoCzAHTv1sG1hSFo=
    on:
        repo: mozilla/crontabber
    distributions: "sdist bdist_wheel"
